---
# =============================================================================
# Local Inventory
# =============================================================================
# This inventory file is used for running the playbook on the local machine.
# =============================================================================

all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
